#!/bin/bash
#: Title       : s1
#: Date        : 13-08-2017
#: Author      : "Amadeu Cavalcante" <amadeu01@gmail.com>
#: Version     : 1.0
#: Description : create folder at $HOME
#: Options     : None
mkdir $HOME/bpl
mkdir $HOME/bpl/bin
mkdir $HOME/bpl/scripts
